name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install & set Version
      working-directory: src
      run: |
        npm install
        npm config set git-tag-version false
        npm version ${{ github.event.release.tag_name }}

    - name: Package
      working-directory: src
      run: |
        ./node_modules/.bin/vsce package

    - name: Publish
      if: "!github.event.release.prerelease"
      working-directory: src
      run: |
        ./node_modules/.bin/vsce publish -p ${{ secrets.DEV_AZURE_PAT }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: '${{ github.event.release.upload_url }}' 
        asset_path: ./src/${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.vsix
        asset_name: ./${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.vsix
        asset_content_type: application/zip
